// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfipygmkwdozmiuwoine.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmaXB5Z21rd2Rvem1pdXdvaW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTUyNzksImV4cCI6MjA3NDMzMTI3OX0.CmZNi9T9gmIFwIBx_J0KZM74RS2_xP21O9g3aJ95WNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});